# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myfirst_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1090, 570)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:/lcd/other/icon/hht.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(64, 38))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 1061, 511))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.setupbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.setupbutton.setObjectName("setupbutton")
        self.verticalLayout.addWidget(self.setupbutton)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("E:/lcd/other/icon/向下.png"))
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.selectbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.selectbutton.setObjectName("selectbutton")
        self.verticalLayout.addWidget(self.selectbutton)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("E:/lcd/other/icon/向下.png"))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.configurebutton = QtWidgets.QPushButton(self.layoutWidget)
        self.configurebutton.setObjectName("configurebutton")
        self.verticalLayout.addWidget(self.configurebutton)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("E:/lcd/other/icon/向下.png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.runbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.runbutton.setObjectName("runbutton")
        self.verticalLayout.addWidget(self.runbutton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.setup = QtWidgets.QWidget()
        self.setup.setObjectName("setup")
        self.gridLayoutWidget = QtWidgets.QWidget(self.setup)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 30, 641, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 1, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 1, 1, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 1, 3, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 3, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 3, 1, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 3, 2, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 3, 3, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 5, 0, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 5, 1, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 5, 2, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout.addWidget(self.lineEdit_17, 5, 3, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.setup)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(270, 210, 331, 201))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 3, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 4, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 6, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 4, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 5, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 2, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 3, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 5, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 1, 0, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_2.addWidget(self.lineEdit_18, 6, 1, 1, 1)
        self.turnonbtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.turnonbtn.setObjectName("turnonbtn")
        self.gridLayout_2.addWidget(self.turnonbtn, 1, 2, 1, 1)
        self.vgabtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.vgabtn.setObjectName("vgabtn")
        self.gridLayout_2.addWidget(self.vgabtn, 5, 2, 1, 1)
        self.turnoffbtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.turnoffbtn.setObjectName("turnoffbtn")
        self.gridLayout_2.addWidget(self.turnoffbtn, 2, 2, 1, 1)
        self.volumesetbtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.volumesetbtn.setObjectName("volumesetbtn")
        self.gridLayout_2.addWidget(self.volumesetbtn, 3, 2, 1, 1)
        self.blsetbtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.blsetbtn.setObjectName("blsetbtn")
        self.gridLayout_2.addWidget(self.blsetbtn, 4, 2, 1, 1)
        self.hdmibtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.hdmibtn.setObjectName("hdmibtn")
        self.gridLayout_2.addWidget(self.hdmibtn, 6, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 0, 0, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_2.addWidget(self.lineEdit_19, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.setup)
        self.label_31.setGeometry(QtCore.QRect(270, 180, 81, 20))
        self.label_31.setObjectName("label_31")
        self.tabWidget.addTab(self.setup, "")
        self.selecttests = QtWidgets.QWidget()
        self.selecttests.setObjectName("selecttests")
        self.treeWidget = QtWidgets.QTreeWidget(self.selecttests)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 831, 431))
        self.treeWidget.setObjectName("treeWidget")
        self.selectedbutton = QtWidgets.QPushButton(self.selecttests)
        self.selectedbutton.setGeometry(QtCore.QRect(240, 450, 75, 23))
        self.selectedbutton.setObjectName("selectedbutton")
        self.allselectbtn = QtWidgets.QPushButton(self.selecttests)
        self.allselectbtn.setGeometry(QtCore.QRect(20, 450, 75, 23))
        self.allselectbtn.setObjectName("allselectbtn")
        self.notallselectbtn = QtWidgets.QPushButton(self.selecttests)
        self.notallselectbtn.setGeometry(QtCore.QRect(110, 450, 75, 23))
        self.notallselectbtn.setObjectName("notallselectbtn")
        self.tabWidget.addTab(self.selecttests, "")
        self.configure = QtWidgets.QWidget()
        self.configure.setObjectName("configure")
        self.layoutWidget1 = QtWidgets.QWidget(self.configure)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 151, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.combobox = QtWidgets.QComboBox(self.layoutWidget1)
        self.combobox.setEditable(False)
        self.combobox.setObjectName("combobox")
        self.horizontalLayout_2.addWidget(self.combobox)
        self.tableWidget = QtWidgets.QTableWidget(self.configure)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 931, 441))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget.addTab(self.configure, "")
        self.connect = QtWidgets.QWidget()
        self.connect.setObjectName("connect")
        self.tabWidget.addTab(self.connect, "")
        self.result = QtWidgets.QWidget()
        self.result.setObjectName("result")
        self.label_21 = QtWidgets.QLabel(self.result)
        self.label_21.setGeometry(QtCore.QRect(70, 60, 111, 16))
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.result)
        self.label_22.setGeometry(QtCore.QRect(70, 80, 111, 16))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.result)
        self.label_23.setGeometry(QtCore.QRect(70, 40, 111, 16))
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.result)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 941, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget.addTab(self.result, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1090, 23))
        self.menubar.setObjectName("menubar")
        self.menuHELLO = QtWidgets.QMenu(self.menubar)
        self.menuHELLO.setObjectName("menuHELLO")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.menuHELLO.addAction(self.actionopen)
        self.menuHELLO.addAction(self.actionsave)
        self.menubar.addAction(self.menuHELLO.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HHT Overseas R&D Test Tool beta V0.0"))
        self.label_4.setText(_translate("MainWindow", "Task Flow"))
        self.setupbutton.setText(_translate("MainWindow", "Set up"))
        self.selectbutton.setText(_translate("MainWindow", "Select tests"))
        self.configurebutton.setText(_translate("MainWindow", "Configure"))
        self.runbutton.setText(_translate("MainWindow", "Start"))
        self.label_8.setText(_translate("MainWindow", "主板型号"))
        self.label_6.setText(_translate("MainWindow", "产品型号"))
        self.label_7.setText(_translate("MainWindow", "测试阶段"))
        self.label_12.setText(_translate("MainWindow", "触控方案"))
        self.label_13.setText(_translate("MainWindow", "固件版本"))
        self.label_14.setText(_translate("MainWindow", "样机提供时间"))
        self.label_11.setText(_translate("MainWindow", "OPS转接板"))
        self.label_16.setText(_translate("MainWindow", "测试时间"))
        self.label_15.setText(_translate("MainWindow", "测试人员"))
        self.label_5.setText(_translate("MainWindow", "电源板型号"))
        self.label_10.setText(_translate("MainWindow", " 前置按键板"))
        self.label_9.setText(_translate("MainWindow", "PANEL"))
        self.label_26.setText(_translate("MainWindow", "音量"))
        self.label_27.setText(_translate("MainWindow", "背光"))
        self.label_29.setText(_translate("MainWindow", "HDMI"))
        self.label_28.setText(_translate("MainWindow", "VGA"))
        self.label_25.setText(_translate("MainWindow", "关机"))
        self.label_24.setText(_translate("MainWindow", "开机"))
        self.turnonbtn.setText(_translate("MainWindow", "Send"))
        self.vgabtn.setText(_translate("MainWindow", "Send"))
        self.turnoffbtn.setText(_translate("MainWindow", "Send"))
        self.volumesetbtn.setText(_translate("MainWindow", "Send"))
        self.blsetbtn.setText(_translate("MainWindow", "Send"))
        self.hdmibtn.setText(_translate("MainWindow", "Send"))
        self.label_30.setText(_translate("MainWindow", "Baud"))
        self.label_31.setText(_translate("MainWindow", "串口设置："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setup), _translate("MainWindow", "Set Up"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "大屏测试："))
        self.selectedbutton.setText(_translate("MainWindow", "OK"))
        self.allselectbtn.setText(_translate("MainWindow", "全选"))
        self.notallselectbtn.setText(_translate("MainWindow", "全不选"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.selecttests), _translate("MainWindow", "Select Tests"))
        self.label_18.setText(_translate("MainWindow", "串口选择："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configure), _translate("MainWindow", "Configure"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.connect), _translate("MainWindow", "Connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.result), _translate("MainWindow", "Result"))
        self.menuHELLO.setTitle(_translate("MainWindow", "File"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionsave.setText(_translate("MainWindow", "save"))

